name: Benchmark tests

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.
      
      - name: Run benchmark
        run: go test -tags bn256 -benchmem -benchtime=1s -run="BenchmarkChunkedUploadChunkReader" -bench="BenchmarkChunkedUploadChunkReader"   ./... | tee ./benchmark.txt
 
      # Run `github-action-benchmark` action
      - name: Push benchmark report
        uses: rhysd/github-action-benchmark@v1
        with:
          name: 0chain/gosdk Benchmark
          tool: 'go'
          output-file-path: benchmark.txt
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GOSDK }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true