name: TRIGGER_0PROXY

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of 0proxy to build'
        required: true
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GOSDK }}

jobs:        
  zproxy:
    name: Triggering 0proxy Build
    runs-on: ubuntu-20.04
    
    
    steps:
    - name:
      id: get_tag
      run: |
          JSON=$(echo {\"latest_tag\":\"$TAG\"})
          echo ::set-output name=JSON::${JSON}
      env:
        TAG: ${{ github.event.inputs.latest_tag }}

    - name: Triggering 0proxy Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: 0proxy
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build.yml
        ref: ${{ github.event.inputs.branch_ref }} 
        inputs: {"latest_tag":"$TAG"}
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
      env:
        TAG: ${{ github.event.inputs.latest_tag }}

    - name: Completing Trigger
      run: |
        echo "Tag ${{ github.event.inputs.latest_tag }}."
        echo "Tage_env "$LATEST_TAG"."
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)