name: GOSDK_RELEASE

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of 0proxy to build'
        required: true
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GOSDK }}

jobs:        
  zproxy:
    name: Triggering 0proxy build
    runs-on: ubuntu-20.04
    
    steps:    
    - name: Triggering 0proxy build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: 0proxy
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build.yml
        ref: $BRANCH_REF
        inputs: ${{ env.LATEST_TAG }}
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
      env:
        BRANCH_REF: ${{ github.event.inputs.branch_ref }}
        LATEST_TAG: ${{ github.event.inputs.latest_tag }}
      