name: TRIGGER_0BOX

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of 0box to build'
        required: true
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GOSDK }}

jobs:        
  zdns:
    name: Triggering 0box Build
    runs-on: ubuntu-20.04
    
    steps:    
    - name: Triggering 0box Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: 0box
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build.yml
        ref: ${{ github.event.inputs.branch_ref }} 
        inputs: '{"latest_tag":"$LATEST_TAG" }'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
      env:
        LATEST_TAG: ${{ github.event.inputs.latest_tag }}

    - name: Completing Trigger
      run: |
        echo "Tag ${{ github.event.inputs.latest_tag }}."
        echo "Tage_env "$LATEST_TAG"."
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
      