name: TRIGGER_0DNS

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of 0dns to build'
        required: true
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GOSDK }}

jobs:        
  zproxy:
    name: Triggering 0dns Build
    runs-on: ubuntu-20.04
    
    steps:    
    - name: Triggering 0dns Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: 0dns
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build.yml
        ref: ${{ github.event.inputs.branch_ref }} 
        inputs: '{"latest_tag":"no"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
      env:
        LATEST_TAG: ${{ github.event.inputs.latest_tag }}
    
    - name: Completing Trigger
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
      